// Token Actions

export const LOGIN = 'LOGIN';
export const REQUEST_SESSION_TOKEN = 'REQUEST_SESSION_TOKEN';
export const RECEIVE_SESSION_TOKEN = 'RECEIVE_SESSION_TOKEN';
export const ERROR_REQUEST_SESSION_TOKEN = 'ERROR_REQUEST_SESSION_TOKEN';
export const REQUEST_EMAIL_SESSION_TOKEN = 'REQUEST_EMAIL_SESSION_TOKEN';
export const RECEIVE_FBAT = 'RECEIVE_FBAT';
export const PUSH_ROUTE = 'PUSH_ROUTE';
export const POP_ROUTE = 'POP_ROUTE';

// API Actions

export const REQUEST_FETCH_EVENTS = 'REQUEST_FETCH_EVENTS';
export const RECEIVE_EVENTS = 'RECEIVE_EVENTS';
export const ERROR_FETCH_EVENTS = 'ERROR_FETCH_EVENTS';
export const POSTING_EVENTS = 'POSTING_EVENTS';
export const POST_EVENT_CONFIRMATION = 'POST_EVENT_CONFIRMATION';
export const ERROR_POST_EVENT = 'ERROR_POST_EVENT';

// User-Event Actions

export const LIKE_EVENT = 'LIKE_EVENT';
export const DISLIKE_EVENT = 'DISLIKE_EVENT';
export const REMOVE_SEEN_EVENT = 'REMOVE_SEEN_EVENT';

// Facebook Actions

export const REQUEST_USER_PROFILE = 'REQUEST_USER_PROFILE';
export const RECEIVE_USER_PROFILE = 'RECEIVE_USER_PROFILE';
export const ERROR_REQUEST_USER_PROFILE = 'ERROR_REQUEST_USER_PROFILE';
